### PR TITLE
BUGFIX: Fix wrong detection of dimensions prefix

### LINKED ISSUE #8: With supportEmptySegmentForDimensions being false, no route matches
When empty dimension segments are not supported, the "not found" path that is generated internally is wrong and results in an error:

```
Uri with path "http://domain.tld/404" could not be found.
```

### PR DESCRIPTION
**Pull request by kdambekalns**
This fixes a simple error when comparing the count of dimension presets
against the number of exploded parts of the first URI path segment.

Fixes #8

### CODE REVIEW

File: Classes/MOC/NotFound/ViewHelpers/RequestViewHelper.php [hunk 1]
```diff
@@ -134,7 +134,7 @@ protected function appendFirstUriPartIfValidDimension(&$path) {
 				}
 			}
 		} else {
-			if (count($firstUriPartExploded) === count($dimensionPresets)) {
+			if (count($firstUriPartExploded) !== count($dimensionPresets)) {
```
Comment (aertmann) [inline Classes/MOC/NotFound/ViewHelpers/RequestViewHelper.php:137]: seems to correspond with https://github.com/neos/neos-development-collection/blob/4a1495e0e5d6eff49bb037b380ca03f5544ddc66/TYPO3.Neos/Classes/TYPO3/Neos/Routing/FrontendNodeRoutePartHandler.php#L538

**Comment by aertmann** [comment]
hey @kdambekalns thanks for the fix
